FROM golang:1.24-alpine

WORKDIR app/

COPY go.mod go.sum ./

RUN go mod download

COPY cmd/api-gateway/ ./cmd/api-gateway/
COPY logger/ ./logger/
COPY config/ ./config/
COPY gen/ ./gen/
COPY .env ./.env
COPY internal/api-gateway/ ./internal/api-gateway/
COPY internal/infrastructure/ ./internal/infrastructure/
COPY internal/entity/ ./internal/entity/

RUN go build -o api cmd/api-gateway/main.go

EXPOSE 8080

CMD ["./api"]